parameters:
    - name: env
      type: string
    - name: projectName
      type: string
    - name: serviceConnection
      type: string
    - name: location
      type: string
    - name: customerName
      type: string

jobs:
    - deployment: DeployInfrastructure
      displayName: Deploy infrastructure
      environment: ${{ parameters.env }}
      strategy:
          runOnce:
              deploy:
                  steps:
                      - checkout: self

                      - powershell: |
                            $letter = '${{parameters.env}}'.substring(0, 1)
                            Write-Host $letter
                            Write-Host "##vso[task.setvariable variable=envLetter;isSecret=false;]$letter"
                        displayName: "Set variable envLetter"

                      - task: AzureCLI@2
                        displayName: Deploy ${{ parameters.projectName }} resources
                        name: EnvironmentDeployment
                        inputs:
                          azureSubscription: ${{ parameters.serviceConnection }}
                          scriptType: ps
                          scriptLocation: scriptPath
                          scriptPath: deploy.ps1
                          arguments: '-projectName "${{ parameters.projectName }}" -env "${{ parameters.env }}" -location "${{ parameters.location }}" -customerName "${{ parameters.customerName}}'